apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        api: external
    spec:
      containers:
      - image: testnasu/udagram-frontend-a:latest
        name: frontend-a
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "2048Mi"
            cpu: "600m"
          limits:
            memory: "2048Mi"
            cpu: "600m"
      restartPolicy: Always
