apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  - name: "8200"
    port: 8200
    targetPort: 80
  selector:
    app: frontend
