name: Docker Images CI
concurrency:
  group: udagram-docker-images-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
'on':
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: udagram-api-feed
            path: ./udagram-api-feed
          - image: udagram-api-user
            path: ./udagram-api-user
          - image: udagram-frontend-a
            path: ./udagram-frontend-a
          - image: udagram-frontend-b
            path: ./udagram-frontend-b
          - image: reverseproxy
            path: ./udagram-reverseproxy

    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Print Tag
      id: version
      run: |
        tag="${{ github.ref }}"
        tag="${tag#refs/tags/}" # Removes "refs/tags/" from the reference
        echo "Tag value: $tag"
        echo "tag=$tag" >> "$GITHUB_OUTPUT"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      if: GitHub.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ${{ matrix.path }}
        file: ${{ matrix.path }}/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.REGISTRY }}/${{ matrix.image }}:latest
          ${{ secrets.REGISTRY }}/${{ matrix.image }}:${{ steps.version.outputs.tag }}
