name: Docker Images CI
concurrency:
  group: udagram-docker-images-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
'on':
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: udagram-api-feed
            path: ./udagram-api-feed
            label: backend-feed
          - image: udagram-api-user
            path: ./udagram-api-user
            label: backend-user
          - image: udagram-frontend-a
            path: ./udagram-frontend-a
            label: frontend-a
          - image: udagram-frontend-b
            path: ./udagram-frontend-b
            label: frontend-b
          - image: reverseproxy
            path: ./udagram-reverseproxy
            label: reverseproxy

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Print Tag
      id: version
      run: |
        tag="${{ github.ref }}"
        tag="${tag#refs/tags/}" # Removes "refs/tags/" from the reference
        echo "Tag value: $tag"
        echo "tag=$tag" >> "$GITHUB_OUTPUT"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      if: GitHub.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ matrix.path }}
        file: ${{ matrix.path }}/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.REGISTRY }}/${{ matrix.image }}:latest
          ${{ secrets.REGISTRY }}/${{ matrix.image }}:${{ steps.version.outputs.tag }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      id: install-kubectll

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Update kube config
      run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER }}

    - name: Deploy to EKS
      run: |
        kubectl set image deployment/${{ matrix.label }} ${{ matrix.label }}=${{ secrets.REGISTRY }}/${{ matrix.image }}:${{ steps.version.outputs.tag }}
